DROP TABLE IF EXISTS test_execution CASCADE;
DROP TABLE IF EXISTS work_execution CASCADE;
DROP TABLE IF EXISTS test_step CASCADE;
DROP TABLE IF EXISTS work_step CASCADE;
DROP TABLE IF EXISTS test_work_list CASCADE;
DROP TABLE IF EXISTS section_work_list CASCADE;
DROP TABLE IF EXISTS tech_card CASCADE;
DROP TABLE IF EXISTS test_card CASCADE;
DROP TABLE IF EXISTS tester_equipment CASCADE;
DROP TABLE IF EXISTS shop_lab CASCADE;
DROP TABLE IF EXISTS equipment CASCADE;
DROP TABLE IF EXISTS laboratory CASCADE;
DROP TABLE IF EXISTS other_instance CASCADE;
DROP TABLE IF EXISTS hangglider_instance CASCADE;
DROP TABLE IF EXISTS helicopter_instance CASCADE;
DROP TABLE IF EXISTS glider_instance CASCADE;
DROP TABLE IF EXISTS rocket_instance CASCADE;
DROP TABLE IF EXISTS aircraft_instance CASCADE;
DROP TABLE IF EXISTS other_type CASCADE;
DROP TABLE IF EXISTS hangglider_type CASCADE;
DROP TABLE IF EXISTS helicopter_type CASCADE;
DROP TABLE IF EXISTS glider_type CASCADE;
DROP TABLE IF EXISTS rocket_type CASCADE;
DROP TABLE IF EXISTS aircraft_type CASCADE;
DROP TABLE IF EXISTS product_instance CASCADE;
DROP TABLE IF EXISTS product_type CASCADE;
DROP TABLE IF EXISTS product_category CASCADE;
DROP TABLE IF EXISTS tester CASCADE;
DROP TABLE IF EXISTS engineer CASCADE;
DROP TABLE IF EXISTS worker CASCADE;
DROP TABLE IF EXISTS employee CASCADE;
DROP TABLE IF EXISTS brigade CASCADE;
DROP TABLE IF EXISTS section CASCADE;
DROP TABLE IF EXISTS shop CASCADE;

CREATE TABLE shop (
    id_shop      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(100) NOT NULL
);

CREATE TABLE laboratory (
    id_lab       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type         VARCHAR(50) NOT NULL,
    name         VARCHAR(100)
);

CREATE TABLE product_category (
    id_category  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(50) NOT NULL
);

CREATE TABLE employee (
    id_employee   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_name     VARCHAR(100) NOT NULL,
    first_name    VARCHAR(100) NOT NULL,
    middle_name   VARCHAR(100),
    birth_date    DATE,
    education     VARCHAR(100),
    hire_date     DATE NOT NULL,
    prior_exp     INT,
    address       VARCHAR(200),
    phone         VARCHAR(20),
    salary        NUMERIC(10,2)
);

CREATE TABLE section (
    id_section    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    id_shop       INT NOT NULL REFERENCES shop(id_shop) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE brigade (
    id_brigade    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    id_section    INT NOT NULL REFERENCES section(id_section) ON DELETE RESTRICT ON UPDATE CASCADE,
    id_foreman    INT NULL
);

CREATE TABLE worker (
    id_employee   INT PRIMARY KEY REFERENCES employee(id_employee) ON DELETE RESTRICT ON UPDATE CASCADE,
    profession    VARCHAR(100) NOT NULL,
    rank          INT CHECK (rank BETWEEN 1 AND 6),
    is_foreman    BOOLEAN DEFAULT FALSE,
    id_brigade    INT NOT NULL REFERENCES brigade(id_brigade) ON DELETE RESTRICT ON UPDATE CASCADE
);

ALTER TABLE brigade ADD CONSTRAINT fk_foreman FOREIGN KEY (id_foreman) REFERENCES worker(id_employee) ON DELETE SET NULL ON UPDATE CASCADE;

CREATE TABLE engineer (
    id_employee   INT PRIMARY KEY REFERENCES employee(id_employee) ON DELETE RESTRICT ON UPDATE CASCADE,
    category      VARCHAR(50) NOT NULL,
    position      VARCHAR(100) NOT NULL
);

CREATE TABLE tester (
    id_employee   INT PRIMARY KEY REFERENCES employee(id_employee) ON DELETE RESTRICT ON UPDATE CASCADE,
    specialization VARCHAR(100) NOT NULL,
    id_lab        INT NOT NULL REFERENCES laboratory(id_lab) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE product_type (
    id_type       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    id_category   INT NOT NULL REFERENCES product_category(id_category) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE product_instance (
    serial_number INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status        VARCHAR(20) NOT NULL CHECK (status IN ('in_assembly', 'under_test', 'ready')),
    id_shop       INT NOT NULL REFERENCES shop(id_shop) ON DELETE RESTRICT ON UPDATE CASCADE,
    id_type       INT NOT NULL REFERENCES product_type(id_type) ON DELETE RESTRICT ON UPDATE CASCADE,
    weight        NUMERIC(10,2),
    material      VARCHAR(100),
    batch         VARCHAR(50)
);

CREATE TABLE aircraft_instance (
    serial_number INT PRIMARY KEY REFERENCES product_instance(serial_number) ON DELETE CASCADE ON UPDATE CASCADE,
    id_type       INT NOT NULL
);

CREATE TABLE rocket_instance (
    serial_number INT PRIMARY KEY REFERENCES product_instance(serial_number) ON DELETE CASCADE ON UPDATE CASCADE,
    id_type       INT NOT NULL
);

CREATE TABLE glider_instance (
    serial_number INT PRIMARY KEY REFERENCES product_instance(serial_number) ON DELETE CASCADE ON UPDATE CASCADE,
    id_type       INT NOT NULL
);

CREATE TABLE helicopter_instance (
    serial_number INT PRIMARY KEY REFERENCES product_instance(serial_number) ON DELETE CASCADE ON UPDATE CASCADE,
    id_type       INT NOT NULL
);

CREATE TABLE hangglider_instance (
    serial_number INT PRIMARY KEY REFERENCES product_instance(serial_number) ON DELETE CASCADE ON UPDATE CASCADE,
    id_type       INT NOT NULL
);

CREATE TABLE other_instance (
    serial_number INT PRIMARY KEY REFERENCES product_instance(serial_number) ON DELETE CASCADE ON UPDATE CASCADE,
    id_type       INT NOT NULL
);

CREATE TABLE aircraft_type (
    id_type       INT PRIMARY KEY REFERENCES product_type(id_type) ON DELETE CASCADE ON UPDATE CASCADE,
    purpose       VARCHAR(100),
    parameters    TEXT
);

CREATE TABLE rocket_type (
    id_type       INT PRIMARY KEY REFERENCES product_type(id_type) ON DELETE CASCADE ON UPDATE CASCADE,
    purpose       VARCHAR(100),
    parameters    TEXT
);

CREATE TABLE glider_type (
    id_type       INT PRIMARY KEY REFERENCES product_type(id_type) ON DELETE CASCADE ON UPDATE CASCADE,
    parameters    TEXT
);

CREATE TABLE helicopter_type (
    id_type       INT PRIMARY KEY REFERENCES product_type(id_type) ON DELETE CASCADE ON UPDATE CASCADE,
    parameters    TEXT
);

CREATE TABLE hangglider_type (
    id_type       INT PRIMARY KEY REFERENCES product_type(id_type) ON DELETE CASCADE ON UPDATE CASCADE,
    parameters    TEXT
);

CREATE TABLE other_type (
    id_type       INT PRIMARY KEY REFERENCES product_type(id_type) ON DELETE CASCADE ON UPDATE CASCADE,
    name          VARCHAR(100),
    parameters    TEXT
);

ALTER TABLE aircraft_instance ADD CONSTRAINT fk_aircraft_type FOREIGN KEY (id_type) REFERENCES aircraft_type(id_type) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE rocket_instance   ADD CONSTRAINT fk_rocket_type   FOREIGN KEY (id_type) REFERENCES rocket_type(id_type)   ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE glider_instance   ADD CONSTRAINT fk_glider_type   FOREIGN KEY (id_type) REFERENCES glider_type(id_type)   ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE helicopter_instance ADD CONSTRAINT fk_helicopter_type FOREIGN KEY (id_type) REFERENCES helicopter_type(id_type) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE hangglider_instance ADD CONSTRAINT fk_hangglider_type FOREIGN KEY (id_type) REFERENCES hangglider_type(id_type) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE other_instance    ADD CONSTRAINT fk_other_type    FOREIGN KEY (id_type) REFERENCES other_type(id_type)    ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE TABLE equipment (
    id_equipment   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(100) NOT NULL,
    model          VARCHAR(100),
    id_lab         INT NOT NULL REFERENCES laboratory(id_lab) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE tester_equipment (
    id_tester      INT NOT NULL REFERENCES tester(id_employee) ON DELETE CASCADE ON UPDATE CASCADE,
    id_equipment   INT NOT NULL REFERENCES equipment(id_equipment) ON DELETE CASCADE ON UPDATE CASCADE,
    assignment_date DATE,
    PRIMARY KEY (id_tester, id_equipment)
);

CREATE TABLE shop_lab (
    id_shop        INT NOT NULL REFERENCES shop(id_shop) ON DELETE CASCADE ON UPDATE CASCADE,
    id_lab         INT NOT NULL REFERENCES laboratory(id_lab) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY (id_shop, id_lab)
);

CREATE TABLE tech_card (
    id_card        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_type        INT NOT NULL REFERENCES product_type(id_type) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE section_work_list (
    id_work        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_section     INT NOT NULL REFERENCES section(id_section) ON DELETE RESTRICT ON UPDATE CASCADE,
    work_name      VARCHAR(100) NOT NULL,
    description    TEXT
);

CREATE TABLE work_step (
    id_step        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_card        INT NOT NULL REFERENCES tech_card(id_card) ON DELETE CASCADE ON UPDATE CASCADE,
    id_work        INT NOT NULL REFERENCES section_work_list(id_work) ON DELETE RESTRICT ON UPDATE CASCADE,
    step_number    INT NOT NULL,
    UNIQUE (id_card, id_work),
    UNIQUE (id_card, step_number)
);

CREATE TABLE test_card (
    id_test_card   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_type        INT NOT NULL REFERENCES product_type(id_type) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE test_work_list (
    id_test_work   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_equipment   INT NOT NULL REFERENCES equipment(id_equipment) ON DELETE RESTRICT ON UPDATE CASCADE,
    test_name      VARCHAR(100) NOT NULL
);

CREATE TABLE test_step (
    id_step        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_test_card   INT NOT NULL REFERENCES test_card(id_test_card) ON DELETE CASCADE ON UPDATE CASCADE,
    id_test_work   INT NOT NULL REFERENCES test_work_list(id_test_work) ON DELETE RESTRICT ON UPDATE CASCADE,
    step_number    INT NOT NULL,
    UNIQUE (id_test_card, id_test_work),
    UNIQUE (id_test_card, step_number)
);

CREATE TABLE work_execution (
    id_execution   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serial_number  INT NOT NULL REFERENCES product_instance(serial_number) ON DELETE CASCADE ON UPDATE CASCADE,
    id_step        INT NOT NULL REFERENCES work_step(id_step) ON DELETE RESTRICT ON UPDATE CASCADE,
    start_date     DATE,
    end_date       DATE,
    status         VARCHAR(20) CHECK (status IN ('in_progress', 'completed', 'defect'))
);

CREATE TABLE test_execution (
    id_test_execution INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serial_number    INT NOT NULL REFERENCES product_instance(serial_number) ON DELETE CASCADE ON UPDATE CASCADE,
    id_test_step     INT NOT NULL REFERENCES test_step(id_step) ON DELETE RESTRICT ON UPDATE CASCADE,
    start_date       DATE,
    end_date         DATE,
    result           VARCHAR(50) CHECK (result IN ('passed', 'failed', 'in_progress')),
    UNIQUE (serial_number, id_test_step)
);


-- Триггеры

CREATE OR REPLACE FUNCTION check_status_transition()
RETURNS TRIGGER AS 
BEGIN
    IF OLD.status = 'in_assembly' AND NEW.status NOT IN ('under_test', 'in_assembly') THEN
        RAISE EXCEPTION 'Product can only move from in_assembly to under_test';
    END IF;
    IF OLD.status = 'under_test' AND NEW.status NOT IN ('ready', 'under_test') THEN
        RAISE EXCEPTION 'Product can only move from under_test to ready';
    END IF;
    IF OLD.status = 'ready' AND NEW.status != 'ready' THEN
        RAISE EXCEPTION 'Ready product cannot change status';
    END IF;
    RETURN NEW;
END;
 LANGUAGE plpgsql;

CREATE TRIGGER trg_check_status_transition
    BEFORE UPDATE OF status ON product_instance
    FOR EACH ROW EXECUTE FUNCTION check_status_transition();

CREATE OR REPLACE FUNCTION check_foreman()
RETURNS TRIGGER AS 
BEGIN
    IF NEW.id_foreman IS NOT NULL THEN
        IF NOT EXISTS (
            SELECT 1 FROM worker
            WHERE id_employee = NEW.id_foreman
              AND id_brigade = NEW.id_brigade
              AND is_foreman = TRUE
        ) THEN
            RAISE EXCEPTION 'Foreman must be a worker of this brigade and have is_foreman = TRUE';
        END IF;
    END IF;
    RETURN NEW;
END;
 LANGUAGE plpgsql;

CREATE TRIGGER trg_check_foreman
    BEFORE INSERT OR UPDATE OF id_foreman, id_brigade ON brigade
    FOR EACH ROW EXECUTE FUNCTION check_foreman();

CREATE OR REPLACE FUNCTION auto_to_testing()
RETURNS TRIGGER AS 
DECLARE
    v_status VARCHAR(20);
    all_completed BOOLEAN;
BEGIN
    IF NEW.status = 'completed' THEN
        SELECT status INTO v_status FROM product_instance WHERE serial_number = NEW.serial_number;
        IF v_status = 'in_assembly' THEN
            SELECT NOT EXISTS (
                SELECT 1
                FROM work_step ws
                JOIN tech_card tc ON ws.id_card = tc.id_card
                JOIN product_instance p ON p.id_type = tc.id_type
                LEFT JOIN work_execution we ON we.serial_number = p.serial_number AND we.id_step = ws.id_step
                WHERE p.serial_number = NEW.serial_number
                  AND (we.status IS NULL OR we.status != 'completed')
            ) INTO all_completed;
            IF all_completed THEN
                UPDATE product_instance SET status = 'under_test' WHERE serial_number = NEW.serial_number;
            END IF;
        END IF;
    END IF;
    RETURN NEW;
END;
 LANGUAGE plpgsql;

CREATE TRIGGER trg_auto_to_testing
    AFTER UPDATE OF status ON work_execution
    FOR EACH ROW EXECUTE FUNCTION auto_to_testing();

CREATE OR REPLACE FUNCTION unique_foreman_per_brigade()
RETURNS TRIGGER AS 
BEGIN
    IF NEW.is_foreman = TRUE THEN
        IF EXISTS (
            SELECT 1 FROM worker
            WHERE id_brigade = NEW.id_brigade
              AND is_foreman = TRUE
              AND id_employee != NEW.id_employee
        ) THEN
            RAISE EXCEPTION 'Brigade already has a foreman';
        END IF;
    END IF;
    RETURN NEW;
END;
 LANGUAGE plpgsql;

CREATE TRIGGER trg_unique_foreman
    BEFORE INSERT OR UPDATE OF is_foreman, id_brigade ON worker
    FOR EACH ROW EXECUTE FUNCTION unique_foreman_per_brigade();

CREATE OR REPLACE FUNCTION prevent_tk_delete()
RETURNS TRIGGER AS 
BEGIN
    IF EXISTS (
        SELECT 1 FROM product_instance
        WHERE id_type = OLD.id_type
          AND status != 'ready'
    ) THEN
        RAISE EXCEPTION 'Cannot delete tech card: unfinished products of this type exist';
    END IF;
    RETURN OLD;
END;
 LANGUAGE plpgsql;

CREATE TRIGGER trg_prevent_tk_delete
    BEFORE DELETE ON tech_card
    FOR EACH ROW EXECUTE FUNCTION prevent_tk_delete();

-- процедуры

CREATE OR REPLACE PROCEDURE start_assembly(
    p_serial INT,
    p_type INT,
    p_shop INT,
    p_weight NUMERIC(10,2) DEFAULT NULL,
    p_material VARCHAR(100) DEFAULT NULL,
    p_batch VARCHAR(50) DEFAULT NULL
)
LANGUAGE plpgsql AS 
DECLARE
    first_step INT;
BEGIN
    INSERT INTO product_instance (serial_number, status, id_shop, id_type, weight, material, batch)
    VALUES (p_serial, 'in_assembly', p_shop, p_type, p_weight, p_material, p_batch);

    SELECT ws.id_step INTO first_step
    FROM tech_card tc
    JOIN work_step ws ON tc.id_card = ws.id_card
    WHERE tc.id_type = p_type
    ORDER BY ws.step_number
    LIMIT 1;

    IF first_step IS NULL THEN
        RAISE EXCEPTION 'No tech card defined for product type %', p_type;
    END IF;

    INSERT INTO work_execution (serial_number, id_step, start_date, status)
    VALUES (p_serial, first_step, CURRENT_DATE, 'in_progress');
END;
;

CREATE OR REPLACE PROCEDURE complete_assembly(p_serial INT)
LANGUAGE plpgsql AS 
DECLARE
    all_completed BOOLEAN;
BEGIN
    SELECT NOT EXISTS (
        SELECT 1
        FROM work_step ws
        JOIN tech_card tc ON ws.id_card = tc.id_card
        JOIN product_instance p ON p.id_type = tc.id_type
        LEFT JOIN work_execution we ON we.serial_number = p.serial_number AND we.id_step = ws.id_step
        WHERE p.serial_number = p_serial
          AND (we.status IS NULL OR we.status != 'completed')
    ) INTO all_completed;

    IF NOT all_completed THEN
        RAISE EXCEPTION 'Not all assembly steps are completed for product %', p_serial;
    END IF;

    UPDATE product_instance SET status = 'ready' WHERE serial_number = p_serial;
END;
;